language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: axeBfCn7s19fNV345mKMKJf/PYeQ7u5OTqat6iQkEEr/3Jtn96s+SCa76txsKoUN985fwVqyYtn9tyVFMNNp52qCWgYTo6c/huSXsQTSQVBaJflU+8yVa1n2pv8wqC9gO0rqOedT/BEM8az2lDivHnHHLBOEmNptZ7EoSAmM2Bh7m6TMtMgsPpd8ZJX0h/HgpIadwQKvBvF9koorRzXf08srvU/whg/6ifo/YMPNMnbgIJq0XNmHAxdc5hUmI2lsO9bnrQl5emw/nbJtvv+WhuVB1NGCSQAweOPtJECgq9XyQit5KkAFdod4ZQI3HNWM1yh1iv1psdxNi9sHDKxud+jfdgJz58iGfn0E9mt6ArYNtvlA0Imba7wA1UcyBUtCWGz58vMZpJ6nyUBeFcCbyjkAF+T9xM1BBTkPBmsuRb4Feve1T8UStgupKZ7esfJdI4mVL99STfzRA+7WpusUGcYVsbQa/GvUQDg1tuEpM/MaabNS2ZGP5nv4jtz1TE95ZXqZ55PkCjy+Y+U+W2FghtPq+UQz79K+gJXs7LThEm9dP+KnCbqa5w37t6UHgRjRe0ebtRS8U9sM4UkhkmQuARkqXcHqO6HGSVoGexHNszOQTDvYyG6LlW5H70656hU60MG21N2O35bC+07+xo0O7k8xuvBOHbLK0qG3uUbsGV8=
  app:
  run: rails db:migrate
